"""initial schema

Revision ID: d5c825947bd9
Revises:
Create Date: 2026-05-21 08:06:53.579147

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5c825947bd9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_profiles",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("origin", sa.Text(), nullable=False),
        sa.Column("storage_state_encrypted", sa.LargeBinary(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_profiles_owner_id"), "auth_profiles", ["owner_id"], unique=False)
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("auth_profile_id", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("headless", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("passed", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.Column("pass_rate", sa.Float(), nullable=False),
        sa.Column("markdown_path", sa.Text(), nullable=False),
        sa.Column("markdown_body", sa.Text(), nullable=False),
        sa.Column("ai_analysis", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_runs_owner_created", "runs", ["owner_id", "created_at"], unique=False)
    op.create_index(op.f("ix_runs_owner_id"), "runs", ["owner_id"], unique=False)
    op.create_index(op.f("ix_runs_status"), "runs", ["status"], unique=False)
    op.create_table(
        "user_settings",
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("anthropic_key_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("gemini_key_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("default_model", sa.String(length=128), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("owner_id"),
    )
    op.create_table(
        "crawls",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("start_url", sa.Text(), nullable=False),
        sa.Column("max_pages", sa.Integer(), nullable=False),
        sa.Column("same_origin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_crawls_owner_id"), "crawls", ["owner_id"], unique=False)
    op.create_index(op.f("ix_crawls_run_id"), "crawls", ["run_id"], unique=False)
    op.create_table(
        "flows",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("page_id", sa.String(length=64), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("steps", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "run_id"),
    )
    op.create_index(op.f("ix_flows_owner_id"), "flows", ["owner_id"], unique=False)
    op.create_index(op.f("ix_flows_run_id"), "flows", ["run_id"], unique=False)
    op.create_table(
        "healing_attempts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("test_case_id", sa.String(length=64), nullable=False),
        sa.Column("test_case_name", sa.Text(), nullable=False),
        sa.Column("original_selector", sa.Text(), nullable=False),
        sa.Column("new_selector", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_healing_attempts_owner_id"), "healing_attempts", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_healing_attempts_run_id"), "healing_attempts", ["run_id"], unique=False
    )
    op.create_table(
        "results",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("test_case_id", sa.String(length=64), nullable=False),
        sa.Column("test_case_name", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("screenshot_path", sa.Text(), nullable=True),
        sa.Column("stdout", sa.Text(), nullable=False),
        sa.Column("stderr", sa.Text(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("healed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_results_owner_id"), "results", ["owner_id"], unique=False)
    op.create_index(op.f("ix_results_run_id"), "results", ["run_id"], unique=False)
    op.create_index(op.f("ix_results_test_case_id"), "results", ["test_case_id"], unique=False)
    op.create_table(
        "run_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("phase", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_run_events_owner_id"), "run_events", ["owner_id"], unique=False)
    op.create_index(op.f("ix_run_events_run_id"), "run_events", ["run_id"], unique=False)
    op.create_index("ix_run_events_run_seq", "run_events", ["run_id", "seq"], unique=False)
    op.create_table(
        "test_cases",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("flow_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("playwright_code", sa.Text(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "run_id"),
    )
    op.create_index(op.f("ix_test_cases_owner_id"), "test_cases", ["owner_id"], unique=False)
    op.create_index(op.f("ix_test_cases_run_id"), "test_cases", ["run_id"], unique=False)
    op.create_table(
        "pages",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=False),
        sa.Column("crawl_id", sa.String(length=64), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("discovered_from", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["crawl_id"], ["crawls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pages_crawl_id"), "pages", ["crawl_id"], unique=False)
    op.create_index(op.f("ix_pages_owner_id"), "pages", ["owner_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pages_owner_id"), table_name="pages")
    op.drop_index(op.f("ix_pages_crawl_id"), table_name="pages")
    op.drop_table("pages")
    op.drop_index(op.f("ix_test_cases_run_id"), table_name="test_cases")
    op.drop_index(op.f("ix_test_cases_owner_id"), table_name="test_cases")
    op.drop_table("test_cases")
    op.drop_index("ix_run_events_run_seq", table_name="run_events")
    op.drop_index(op.f("ix_run_events_run_id"), table_name="run_events")
    op.drop_index(op.f("ix_run_events_owner_id"), table_name="run_events")
    op.drop_table("run_events")
    op.drop_index(op.f("ix_results_test_case_id"), table_name="results")
    op.drop_index(op.f("ix_results_run_id"), table_name="results")
    op.drop_index(op.f("ix_results_owner_id"), table_name="results")
    op.drop_table("results")
    op.drop_index(op.f("ix_healing_attempts_run_id"), table_name="healing_attempts")
    op.drop_index(op.f("ix_healing_attempts_owner_id"), table_name="healing_attempts")
    op.drop_table("healing_attempts")
    op.drop_index(op.f("ix_flows_run_id"), table_name="flows")
    op.drop_index(op.f("ix_flows_owner_id"), table_name="flows")
    op.drop_table("flows")
    op.drop_index(op.f("ix_crawls_run_id"), table_name="crawls")
    op.drop_index(op.f("ix_crawls_owner_id"), table_name="crawls")
    op.drop_table("crawls")
    op.drop_table("user_settings")
    op.drop_index(op.f("ix_runs_status"), table_name="runs")
    op.drop_index(op.f("ix_runs_owner_id"), table_name="runs")
    op.drop_index("ix_runs_owner_created", table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_auth_profiles_owner_id"), table_name="auth_profiles")
    op.drop_table("auth_profiles")
    # ### end Alembic commands ###
